
version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: ramonfrombr/nestapp:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
      - redis
    networks:
      myapp_net:

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      myapp_net:

  redis:    
    image: "bitnami/redis:7.2"
    restart: unless-stopped  
    ports:  
      - 6379:6379 
    volumes:  
      - "redis_data:/bitnami/redis/data"  
    environment:  
      REDIS_PASSWORD: veryhardpassword
      REDIS_PORT: 6379 
      REDIS_DB: 0 
      REDIS_IO_THREADS: 4  
      REDIS_IO_THREADS_DO_READS: yes  
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL  
    networks:  
      myapp_net:

networks:
  myapp_net:

volumes:
  pgdata: {}
  redis_data: